package com.teco.ventago.design_system.theme
//
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.surfaceColorAtElevation
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp


@Composable
fun cardContainerColor(): Color {
    val isDarkTheme = isSystemInDarkTheme()
    return if (isDarkTheme) {
        // Use surface color that adapts elevation for dark mode
        MaterialTheme.colorScheme.surfaceColorAtElevation(4.dp)
    } else {
        // Flat background color for light mode
        MaterialTheme.colorScheme.background
    }
}

@Composable
fun vanishedBackgroundColor(): Color {
    return if (isSystemInDarkTheme()) {
        // Slightly dark tinted version of secondary color
        MaterialTheme.colorScheme.secondary.copy(alpha = 0.15f)
    } else {
        // Your original light "vanished" background
        vanishedBackgroundColor
    }
}


val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val ColorNonVIP = Color(0xFF23425A)
val ColorVIP = Color(0xFFFFCD2E)
val ServiceIssueColor = Color(0x66304FFE)
val FoodIssueColor = Color(0x66FFCC00)
val DeliveryIssueColor = Color(0x26CA0B00)
val Online = Color(0xFF689f38)
val WarningAmber = Color(0xFFFFBF00)
val RedLight = Color(0XFFE05D5D)

// Reservation Status color
val StatusConfirmed = Color(0xBF689f38)
val StatusRejected = Color(0xFFE05D5D)
val StatusModified = Color(0xFFF1AE2F)
val VIPColor = Color(0xFFF1AE2F)
val StatusPending = Color(0xBFe65100)
val StatusOld = Color(0xFF757575)

val graphicSelectedColor = Color(0xFF308868)
val graphicNormalColor = Color(0xFFB0D1C5)

val badgeColorBlue = Color(0xFF2C54CF)
val badgeColorOrange = Color(0xFFE65100)

// Orders Status Color
val NewContainer = Color(0x26006C44)
val NewLabel = Color(0xFF006C44)
val CompletedContainer = Color(0x24374957)
val CompletedLabel = Color(0xFF374957)
val AcceptedContainer = Color(0x26006C44)
val AcceptedLabel = Color(0xFF006C44)
val CancelledContainer = Color(0x29C50000)
val CancelledLabel = Color(0xFF770000)
val PaymentFailedContainer = Color(0x29C50000)
val PaymentFailedLabel = Color(0xFF770000)
val RejectedContainer = Color(0x29C50000)
val RejectedLabel = Color(0xFF770000)
val ProcessingContainer = Color(0x29FF5C00)
val ProcessingLabel = Color(0xFFFF5C00)
val InDeliveryContainer = Color(0x29FF5C00)
val InDeliveryLabel = Color(0xFFFF5C00)
val ReadyForPickupContainer = Color(0x29FF5C00)
val ReadyForPickupLabel = Color(0xFFFF5C00)
val ReadyContainer = Color(0x29FF5C00)
val ReadyLabel = Color(0xFFFF5C00)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Gray80 = Color(0xFFD9D9D9)
val Gray70 = Color(0xFFC6CAD2)
val Gray50 = Color(0xFF949494)
val Gray30 = Color(0xFF434A56)
val Gray20 = Color(0xFF313335)
val Gray10 = Color(0xFF16191D)

val BlueTechnology = Color(0xFF0B1E3E)
val ShimmerColorShades = listOf(
    Color.LightGray.copy(0.9f),
    Color.LightGray.copy(0.2f),
    Color.LightGray.copy(0.9f)
)

private val vanishedBackgroundColor = Color(0xFFF2F1FD)

val primaryLight = Color(0xFF000F22)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0A2540)
val onPrimaryContainerLight = Color(0xFF768DAD)
val secondaryLight = Color(0xFF493EE5)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF635BFF)
val onSecondaryContainerLight = Color(0xFFFEFAFF)
val tertiaryLight = Color(0xFF493EE5)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF635BFF)
val onTertiaryContainerLight = Color(0xFFFEFAFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF9FB)
val onBackgroundLight = Color(0xFF1B1C1E)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1C)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF3F0EF)
val inversePrimaryLight = Color(0xFFB0C8EB)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF0EDED)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryLightMediumContrast = Color(0xFF000F22)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF0A2540)
val onPrimaryContainerLightMediumContrast = Color(0xFF99B1D3)
val secondaryLightMediumContrast = Color(0xFF2100B6)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF5C53F8)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2100B6)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5C53F8)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF9FB)
val onBackgroundLightMediumContrast = Color(0xFF1B1C1E)
val surfaceLightMediumContrast = Color(0xFFFCF8F8)
val onSurfaceLightMediumContrast = Color(0xFF111111)
val surfaceVariantLightMediumContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightMediumContrast = Color(0xFF333738)
val outlineLightMediumContrast = Color(0xFF4F5354)
val outlineVariantLightMediumContrast = Color(0xFF6A6E6E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F0EF)
val inversePrimaryLightMediumContrast = Color(0xFFB0C8EB)
val surfaceDimLightMediumContrast = Color(0xFFC9C6C5)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F3F2)
val surfaceContainerLightMediumContrast = Color(0xFFEBE7E7)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDC)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D1D1)

val primaryLightHighContrast = Color(0xFF000F22)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF0A2540)
val onPrimaryContainerLightHighContrast = Color(0xFFC4DCFF)
val secondaryLightHighContrast = Color(0xFF1A0099)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3522D4)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF1A0099)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3522D4)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAF9FB)
val onBackgroundLightHighContrast = Color(0xFF1B1C1E)
val surfaceLightHighContrast = Color(0xFFFCF8F8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E3E3)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292D2D)
val outlineVariantLightHighContrast = Color(0xFF464A4A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFB0C8EB)
val surfaceDimLightHighContrast = Color(0xFFBBB8B8)
val surfaceBrightLightHighContrast = Color(0xFFFCF8F8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F0EF)
val surfaceContainerLightHighContrast = Color(0xFFE5E2E1)
val surfaceContainerHighLightHighContrast = Color(0xFFD7D4D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C5)

val primaryDark = Color(0xFFB0C8EB)
val onPrimaryDark = Color(0xFF19324D)
val primaryContainerDark = Color(0xFF0A2540)
val onPrimaryContainerDark = Color(0xFF768DAD)
val secondaryDark = Color(0xFFC3C0FF)
val onSecondaryDark = Color(0xFF1D00A5)
val secondaryContainerDark = Color(0xFF635BFF)
val onSecondaryContainerDark = Color(0xFFFEFAFF)
val tertiaryDark = Color(0xFFC3C0FF)
val onTertiaryDark = Color(0xFF1D00A5)
val tertiaryContainerDark = Color(0xFF635BFF)
val onTertiaryContainerDark = Color(0xFFFEFAFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121315)
val onBackgroundDark = Color(0xFFE3E2E5)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C8)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF49607E)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1C)
val surfaceContainerDark = Color(0xFF201F20)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353535)

val primaryDarkMediumContrast = Color(0xFFC8DEFF)
val onPrimaryDarkMediumContrast = Color(0xFF0C2742)
val primaryContainerDarkMediumContrast = Color(0xFF7B92B3)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDBD8FF)
val onSecondaryDarkMediumContrast = Color(0xFF160086)
val secondaryContainerDarkMediumContrast = Color(0xFF8582FF)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFDBD8FF)
val onTertiaryDarkMediumContrast = Color(0xFF160086)
val tertiaryContainerDarkMediumContrast = Color(0xFF8582FF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121315)
val onBackgroundDarkMediumContrast = Color(0xFFE3E2E5)
val surfaceDarkMediumContrast = Color(0xFF131313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444748)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDADDDD)
val outlineDarkMediumContrast = Color(0xFFAFB2B3)
val outlineVariantDarkMediumContrast = Color(0xFF8D9191)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E2E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF324966)
val surfaceDimDarkMediumContrast = Color(0xFF131313)
val surfaceBrightDarkMediumContrast = Color(0xFF454444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1D1E)
val surfaceContainerDarkMediumContrast = Color(0xFF282828)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D3D)

val primaryDarkHighContrast = Color(0xFFE9F0FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFADC4E7)
val onPrimaryContainerDarkHighContrast = Color(0xFF000C1C)
val secondaryDarkHighContrast = Color(0xFFF1EEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBEBCFF)
val onSecondaryContainerDarkHighContrast = Color(0xFF05003A)
val tertiaryDarkHighContrast = Color(0xFFF1EEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBEBCFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF05003A)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF121315)
val onBackgroundDarkHighContrast = Color(0xFFE3E2E5)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444748)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEF0F1)
val outlineVariantDarkHighContrast = Color(0xFFC0C3C4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF324966)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF515050)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF201F20)
val surfaceContainerDarkHighContrast = Color(0xFF313030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474646)
