package com.teco.ventago.core.location


data class Loc(
    val province: String,
    val district: String,
    val corregimiento: String,
    val code: String,          // unique code for the combo (e.g., "1-1-1")
)

object PanamaLocations {
    val LIST: List<Loc> = listOf(
        Loc("BOCAS DEL TORO", "BOCAS DEL TORO", "BOCAS DEL TORO (CABECERA)", "1-1-1"),
        Loc("BOCAS DEL TORO", "BOCAS DEL TORO", "BASTIMENTOS", "1-1-2"),
        Loc("BOCAS DEL TORO", "BOCAS DEL TORO", "CAUCHERO", "1-1-3"),
        Loc("BOCAS DEL TORO", "BOCAS DEL TORO", "PUNTA LAUREL", "1-1-4"),
        Loc("BOCAS DEL TORO", "BOCAS DEL TORO", "TIERRA OSCURA", "1-1-5"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "CHANGUINOLA (CABECERA)", "1-2-1"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "ALMIRANTE", "1-2-2"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "GUABITO", "1-2-3"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "TERIBE", "1-2-4"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "VALLE DEL RISCO", "1-2-5"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "EL EMPALME", "1-2-6"),
        Loc("BOCAS DEL TORO", "CHANGUINOLA", "LAS TABLAS", "1-2-7"),
        Loc("BOCAS DEL TORO", "CHIRIQUI GRANDE", "CHIRIQUI GRANDE (CABECERA)", "1-3-1"),
        Loc("BOCAS DEL TORO", "CHIRIQUI GRANDE", "MIRAMAR", "1-3-2"),
        Loc("BOCAS DEL TORO", "CHIRIQUI GRANDE", "PUNTA PEÑA", "1-3-3"),
        Loc("BOCAS DEL TORO", "CHIRIQUI GRANDE", "PUNTA ROBALO", "1-3-4"),
        Loc("BOCAS DEL TORO", "CHIRIQUI GRANDE", "RAMBALA", "1-3-5"),
        Loc("COCLE", "AGUADULCE", "AGUADULCE (CABECERA)", "2-1-1"),
        Loc("COCLE", "AGUADULCE", "EL CRISTO", "2-1-2"),
        Loc("COCLE", "AGUADULCE", "EL ROBLE", "2-1-3"),
        Loc("COCLE", "AGUADULCE", "POCRI", "2-1-4"),
        Loc("COCLE", "AGUADULCE", "BARRIOS UNIDOS", "2-1-5"),
        Loc("COCLE", "ANTON", "ANTON (CABECERA)", "2-2-1"),
        Loc("COCLE", "ANTON", "CABUYA", "2-2-2"),
        Loc("COCLE", "ANTON", "EL CHIRU", "2-2-3"),
        Loc("COCLE", "ANTON", "EL RETIRO", "2-2-4"),
        Loc("COCLE", "ANTON", "EL VALLE", "2-2-5"),
        Loc("COCLE", "ANTON", "JUAN DIAZ", "2-2-6"),
        Loc("COCLE", "ANTON", "RIO HATO", "2-2-7"),
        Loc("COCLE", "ANTON", "SAN JUAN DE DIOS", "2-2-8"),
        Loc("COCLE", "ANTON", "SANTA RITA", "2-2-9"),
        Loc("COCLE", "ANTON", "CABALLERO", "2-2-10"),
        Loc("COCLE", "LA PINTADA", "LA PINTADA (CABECERA)", "2-3-1"),
        Loc("COCLE", "LA PINTADA", "EL HARINO", "2-3-2"),
        Loc("COCLE", "LA PINTADA", "EL POTRERO", "2-3-3"),
        Loc("COCLE", "LA PINTADA", "LLANO GRANDE", "2-3-4"),
        Loc("COCLE", "LA PINTADA", "PIEDRAS GORDAS", "2-3-5"),
        Loc("COCLE", "LA PINTADA", "LAS LOMAS", "2-3-6"),
        Loc("COCLE", "NATA", "NATA (CABECERA)", "2-4-1"),
        Loc("COCLE", "NATA", "CAPELLANIA", "2-4-2"),
        Loc("COCLE", "NATA", "EL CAÑO", "2-4-3"),
        Loc("COCLE", "NATA", "GUZMAN", "2-4-4"),
        Loc("COCLE", "NATA", "LAS HUACAS", "2-4-5"),
        Loc("COCLE", "NATA", "TOZA", "2-4-6"),
        Loc("COCLE", "OLA", "OLA (CABECERA)", "2-5-1"),
        Loc("COCLE", "OLA", "EL COPE", "2-5-2"),
        Loc("COCLE", "OLA", "EL PALMAR", "2-5-3"),
        Loc("COCLE", "OLA", "EL PICACHO", "2-5-4"),
        Loc("COCLE", "OLA", "LA PAVA", "2-5-5"),
        Loc("COCLE", "PENONOME", "PENONOME (CABECERA)", "2-6-1"),
        Loc("COCLE", "PENONOME", "CAÑAVERAL", "2-6-2"),
        Loc("COCLE", "PENONOME", "COCLE", "2-6-3"),
        Loc("COCLE", "PENONOME", "CHIGUIRI ARRIBA", "2-6-4"),
        Loc("COCLE", "PENONOME", "EL COCO", "2-6-5"),
        Loc("COCLE", "PENONOME", "PAJONAL", "2-6-6"),
        Loc("COCLE", "PENONOME", "RIO GRANDE", "2-6-7"),
        Loc("COCLE", "PENONOME", "RIO INDIO", "2-6-8"),
        Loc("COCLE", "PENONOME", "TOABRE", "2-6-9"),
        Loc("COCLE", "PENONOME", "TULU", "2-6-10"),
        Loc("COLON", "COLON", "BARRIO NORTE", "3-1-1"),
        Loc("COLON", "COLON", "BARRIO SUR", "3-1-2"),
        Loc("COLON", "COLON", "BUENA VISTA", "3-1-3"),
        Loc("COLON", "COLON", "CATIVA", "3-1-4"),
        Loc("COLON", "COLON", "CIRICITO", "3-1-5"),
        Loc("COLON", "COLON", "CRISTOBAL", "3-1-6"),
        Loc("COLON", "COLON", "ESCOBAL", "3-1-7"),
        Loc("COLON", "COLON", "LIMON", "3-1-8"),
        Loc("COLON", "COLON", "NUEVA PROVIDENCIA", "3-1-9"),
        Loc("COLON", "COLON", "PUERTO PILON", "3-1-10"),
        Loc("COLON", "COLON", "SABANITAS", "3-1-11"),
        Loc("COLON", "COLON", "SALAMANCA", "3-1-12"),
        Loc("COLON", "COLON", "SAN JUAN", "3-1-13"),
        Loc("COLON", "COLON", "SANTA ROSA", "3-1-14"),
        Loc("COLON", "CHAGRES", "NUEVO CHAGRES (CABECERA)", "3-2-1"),
        Loc("COLON", "CHAGRES", "ACHIOTE", "3-2-2"),
        Loc("COLON", "CHAGRES", "EL GUABO", "3-2-3"),
        Loc("COLON", "CHAGRES", "LA ENCANTADA", "3-2-4"),
        Loc("COLON", "CHAGRES", "PALMAS BELLAS", "3-2-5"),
        Loc("COLON", "CHAGRES", "PIÑA", "3-2-6"),
        Loc("COLON", "CHAGRES", "SALUD", "3-2-7"),
        Loc("COLON", "DONOSO", "MIGUEL DE LA BORDA (CABECERA)", "3-3-1"),
        Loc("COLON", "DONOSO", "COCLE DEL NORTE", "3-3-2"),
        Loc("COLON", "DONOSO", "EL GUASIMO", "3-3-3"),
        Loc("COLON", "DONOSO", "GOBEA", "3-3-4"),
        Loc("COLON", "DONOSO", "RIO INDIO", "3-3-5"),
        Loc("COLON", "DONOSO", "SAN JOSE DEL GENERAL", "3-3-6"),
        Loc("COLON", "PORTOBELO", "PORTOBELO (CABECERA)", "3-4-1"),
        Loc("COLON", "PORTOBELO", "CACIQUE", "3-4-2"),
        Loc("COLON", "PORTOBELO", "GARROTE", "3-4-3"),
        Loc("COLON", "PORTOBELO", "ISLA GRANDE", "3-4-4"),
        Loc("COLON", "PORTOBELO", "MARIA CHIQUITA", "3-4-5"),
        Loc("COLON", "SANTA ISABEL", "PALENQUE (CABECERA)", "3-5-1"),
        Loc("COLON", "SANTA ISABEL", "CUANGO", "3-5-2"),
        Loc("COLON", "SANTA ISABEL", "MIRAMAR", "3-5-3"),
        Loc("COLON", "SANTA ISABEL", "NOMBRE DE DIOS", "3-5-4"),
        Loc("COLON", "SANTA ISABEL", "PALMIRA", "3-5-5"),
        Loc("COLON", "SANTA ISABEL", "PLAYA CHIQUITA", "3-5-6"),
        Loc("COLON", "SANTA ISABEL", "SANTA ISABEL", "3-5-7"),
        Loc("COLON", "SANTA ISABEL", "VIENTO FRIO", "3-5-8"),
        Loc("CHIRIQUI", "ALANJE", "ALANJE (CABECERA)", "4-1-1"),
        Loc("CHIRIQUI", "ALANJE", "DIVALA", "4-1-2"),
        Loc("CHIRIQUI", "ALANJE", "EL TEJAR", "4-1-3"),
        Loc("CHIRIQUI", "ALANJE", "GUARUMAL", "4-1-4"),
        Loc("CHIRIQUI", "ALANJE", "PALO GRANDE", "4-1-5"),
        Loc("CHIRIQUI", "ALANJE", "QUEREVALO", "4-1-6"),
        Loc("CHIRIQUI", "ALANJE", "SANTO TOMAS", "4-1-7"),
        Loc("CHIRIQUI", "ALANJE", "CANTA GALLO", "4-1-8"),
        Loc("CHIRIQUI", "ALANJE", "NUEVO MEXICO", "4-1-9"),
        Loc("CHIRIQUI", "BARU", "PUERTO ARMUELLES (CABECERA)", "4-2-1"),
        Loc("CHIRIQUI", "BARU", "LIMONES", "4-2-2"),
        Loc("CHIRIQUI", "BARU", "PROGRESO", "4-2-3"),
        Loc("CHIRIQUI", "BARU", "BACO", "4-2-4"),
        Loc("CHIRIQUI", "BARU", "RODOLFO AGUILAR DELGADO", "4-2-5"),
        Loc("CHIRIQUI", "BOQUERON", "BOQUERON (CABECERA)", "4-3-1"),
        Loc("CHIRIQUI", "BOQUERON", "BAGALA", "4-3-2"),
        Loc("CHIRIQUI", "BOQUERON", "CORDILLERA", "4-3-3"),
        Loc("CHIRIQUI", "BOQUERON", "GUABAL", "4-3-4"),
        Loc("CHIRIQUI", "BOQUERON", "GUAYABAL", "4-3-5"),
        Loc("CHIRIQUI", "BOQUERON", "PARAISO", "4-3-6"),
        Loc("CHIRIQUI", "BOQUERON", "PEDREGAL", "4-3-7"),
        Loc("CHIRIQUI", "BOQUERON", "TIJERAS", "4-3-8"),
        Loc("CHIRIQUI", "BOQUETE", "BAJO BOQUETE (CABECERA)", "4-4-1"),
        Loc("CHIRIQUI", "BOQUETE", "CALDERA", "4-4-2"),
        Loc("CHIRIQUI", "BOQUETE", "PALMIRA", "4-4-3"),
        Loc("CHIRIQUI", "BOQUETE", "ALTO BOQUETE", "4-4-4"),
        Loc("CHIRIQUI", "BOQUETE", "JARAMILLO", "4-4-5"),
        Loc("CHIRIQUI", "BOQUETE", "LOS NARANJOS", "4-4-6"),
        Loc("CHIRIQUI", "BUGABA", "LA CONCEPCION (CABECERA)", "4-5-1"),
        Loc("CHIRIQUI", "BUGABA", "ASERRIO DE GARICHE", "4-5-2"),
        Loc("CHIRIQUI", "BUGABA", "BUGABA", "4-5-3"),
        Loc("CHIRIQUI", "BUGABA", "CERRO PUNTA", "4-5-4"),
        Loc("CHIRIQUI", "BUGABA", "GOMEZ", "4-5-5"),
        Loc("CHIRIQUI", "BUGABA", "LA ESTRELLA", "4-5-6"),
        Loc("CHIRIQUI", "BUGABA", "SAN ANDRES", "4-5-7"),
        Loc("CHIRIQUI", "BUGABA", "SANTA MARTA", "4-5-8"),
        Loc("CHIRIQUI", "BUGABA", "SANTA ROSA", "4-5-9"),
        Loc("CHIRIQUI", "BUGABA", "SANTO DOMINGO", "4-5-10"),
        Loc("CHIRIQUI", "BUGABA", "SORTOVA", "4-5-11"),
        Loc("CHIRIQUI", "BUGABA", "VOLCAN", "4-5-12"),
        Loc("CHIRIQUI", "BUGABA", "EL BONGO", "4-5-13"),
        Loc("CHIRIQUI", "DAVID", "DAVID (CABECERA)", "4-6-1"),
        Loc("CHIRIQUI", "DAVID", "BIJAGUAL", "4-6-2"),
        Loc("CHIRIQUI", "DAVID", "COCHEA", "4-6-3"),
        Loc("CHIRIQUI", "DAVID", "CHIRIQUI", "4-6-4"),
        Loc("CHIRIQUI", "DAVID", "GUACA", "4-6-5"),
        Loc("CHIRIQUI", "DAVID", "LAS LOMAS", "4-6-6"),
        Loc("CHIRIQUI", "DAVID", "PEDREGAL", "4-6-7"),
        Loc("CHIRIQUI", "DAVID", "SAN CARLOS", "4-6-8"),
        Loc("CHIRIQUI", "DAVID", "SAN PABLO NUEVO", "4-6-9"),
        Loc("CHIRIQUI", "DAVID", "SAN PABLO VIEJO", "4-6-10"),
        Loc("CHIRIQUI", "DOLEGA", "DOLEGA (CABECERA)", "4-7-1"),
        Loc("CHIRIQUI", "DOLEGA", "DOS RIOS", "4-7-2"),
        Loc("CHIRIQUI", "DOLEGA", "LOS ANASTACIOS", "4-7-3"),
        Loc("CHIRIQUI", "DOLEGA", "POTRERILLOS", "4-7-4"),
        Loc("CHIRIQUI", "DOLEGA", "POTRERILLOS ABAJO", "4-7-5"),
        Loc("CHIRIQUI", "DOLEGA", "ROVIRA", "4-7-6"),
        Loc("CHIRIQUI", "DOLEGA", "TINAJAS", "4-7-7"),
        Loc("CHIRIQUI", "DOLEGA", "LOS ALGARRROBOS", "4-7-8"),
        Loc("CHIRIQUI", "GUALACA", "GUALACA (CABECERA)", "4-8-1"),
        Loc("CHIRIQUI", "GUALACA", "HORNITO", "4-8-2"),
        Loc("CHIRIQUI", "GUALACA", "LOS ANGELES", "4-8-3"),
        Loc("CHIRIQUI", "GUALACA", "PAJA DE SOMBRERO", "4-8-4"),
        Loc("CHIRIQUI", "GUALACA", "RINCON", "4-8-5"),
        Loc("CHIRIQUI", "REMEDIOS", "REMEDIOS (CABECERA)", "4-9-1"),
        Loc("CHIRIQUI", "REMEDIOS", "EL NANCITO", "4-9-2"),
        Loc("CHIRIQUI", "REMEDIOS", "EL PORVENIR", "4-9-3"),
        Loc("CHIRIQUI", "REMEDIOS", "EL PUERTO", "4-9-4"),
        Loc("CHIRIQUI", "REMEDIOS", "SANTA LUCIA", "4-9-5"),
        Loc("CHIRIQUI", "RENACIMIENTO", "RIO SERENO (CABECERA)", "4-10-1"),
        Loc("CHIRIQUI", "RENACIMIENTO", "BREÑON", "4-10-2"),
        Loc("CHIRIQUI", "RENACIMIENTO", "CAÑAS GORDAS", "4-10-3"),
        Loc("CHIRIQUI", "RENACIMIENTO", "MONTE LIRIO", "4-10-4"),
        Loc("CHIRIQUI", "RENACIMIENTO", "PLAZA CAISAN", "4-10-5"),
        Loc("CHIRIQUI", "RENACIMIENTO", "SANTA CRUZ", "4-10-6"),
        Loc("CHIRIQUI", "RENACIMIENTO", "DOMINICAL", "4-10-7"),
        Loc("CHIRIQUI", "RENACIMIENTO", "SANTA CLARA", "4-10-8"),
        Loc("CHIRIQUI", "SAN FELIX", "LAS LAJAS (CABECERA)", "4-11-1"),
        Loc("CHIRIQUI", "SAN FELIX", "JUAY", "4-11-2"),
        Loc("CHIRIQUI", "SAN FELIX", "LAJAS ADENTRO", "4-11-3"),
        Loc("CHIRIQUI", "SAN FELIX", "SAN FELIX", "4-11-4"),
        Loc("CHIRIQUI", "SAN FELIX", "SANTA CRUZ", "4-11-5"),
        Loc("CHIRIQUI", "SAN LORENZO", "HORCONCITOS (CABECERA)", "4-12-1"),
        Loc("CHIRIQUI", "SAN LORENZO", "BOCA CHICA", "4-12-2"),
        Loc("CHIRIQUI", "SAN LORENZO", "BOCA DEL MONTE", "4-12-3"),
        Loc("CHIRIQUI", "SAN LORENZO", "SAN JUAN", "4-12-4"),
        Loc("CHIRIQUI", "SAN LORENZO", "SAN LORENZO", "4-12-5"),
        Loc("CHIRIQUI", "TOLE", "TOLE (CABECERA)", "4-13-1"),
        Loc("CHIRIQUI", "TOLE", "BELLA VISTA", "4-13-2"),
        Loc("CHIRIQUI", "TOLE", "CERRO VIEJO", "4-13-3"),
        Loc("CHIRIQUI", "TOLE", "EL CRISTO", "4-13-4"),
        Loc("CHIRIQUI", "TOLE", "JUSTO FIDEL PALACIOS", "4-13-5"),
        Loc("CHIRIQUI", "TOLE", "LAJAS DE TOLE", "4-13-6"),
        Loc("CHIRIQUI", "TOLE", "POTRERO DE CAÑA", "4-13-7"),
        Loc("CHIRIQUI", "TOLE", "QUEBRADA DE PIEDRA", "4-13-8"),
        Loc("CHIRIQUI", "TOLE", "VELADERO", "4-13-9"),
        Loc("DARIEN", "CHEPIGANA", "LA PALMA (CABECERA)", "5-1-1"),
        Loc("DARIEN", "CHEPIGANA", "CAMOGANTI", "5-1-2"),
        Loc("DARIEN", "CHEPIGANA", "CHEPIGANA", "5-1-3"),
        Loc("DARIEN", "CHEPIGANA", "GARACHINE", "5-1-4"),
        Loc("DARIEN", "CHEPIGANA", "JAQUE", "5-1-5"),
        Loc("DARIEN", "CHEPIGANA", "PUERTO PIÑA", "5-1-6"),
        Loc("DARIEN", "CHEPIGANA", "RIO CONGO", "5-1-7"),
        Loc("DARIEN", "CHEPIGANA", "RIO IGLESIAS", "5-1-8"),
        Loc("DARIEN", "CHEPIGANA", "SAMBU", "5-1-9"),
        Loc("DARIEN", "CHEPIGANA", "SETEGANTI", "5-1-10"),
        Loc("DARIEN", "CHEPIGANA", "TAIMATI", "5-1-11"),
        Loc("DARIEN", "CHEPIGANA", "TUCUTI", "5-1-12"),
        Loc("DARIEN", "CHEPIGANA", "AGUA FRIA", "5-1-13"),
        Loc("DARIEN", "CHEPIGANA", "CUCUNATI", "5-1-14"),
        Loc("DARIEN", "CHEPIGANA", "RIO CONGO ARRIBA", "5-1-15"),
        Loc("DARIEN", "CHEPIGANA", "SANTA FE", "5-1-16"),
        Loc("DARIEN", "PINOGANA", "EL REAL DE SANTA MARIA (CABECE", "5-2-1"),
        Loc("DARIEN", "PINOGANA", "BOCA DE CUPE", "5-2-2"),
        Loc("DARIEN", "PINOGANA", "PAYA", "5-2-3"),
        Loc("DARIEN", "PINOGANA", "PINOGANA", "5-2-4"),
        Loc("DARIEN", "PINOGANA", "PUCURO", "5-2-5"),
        Loc("DARIEN", "PINOGANA", "YAPE", "5-2-6"),
        Loc("DARIEN", "PINOGANA", "YAVIZA", "5-2-7"),
        Loc("DARIEN", "PINOGANA", "METETI", "5-2-8"),
        Loc("DARIEN", "PINOGANA", "COMARCA KUNA DE WARGANDI", "5-2-9"),
        Loc("HERRERA", "CHITRE", "CHITRE (CABECERA)", "6-1-1"),
        Loc("HERRERA", "CHITRE", "LA ARENA", "6-1-2"),
        Loc("HERRERA", "CHITRE", "MONAGRILLO", "6-1-3"),
        Loc("HERRERA", "CHITRE", "LLANO BONITO", "6-1-4"),
        Loc("HERRERA", "CHITRE", "SAN JUAN BAUTISTA", "6-1-5"),
        Loc("HERRERA", "LAS MINAS", "LAS MINAS (CABECERA)", "6-2-1"),
        Loc("HERRERA", "LAS MINAS", "CHEPO", "6-2-2"),
        Loc("HERRERA", "LAS MINAS", "CHUMICAL", "6-2-3"),
        Loc("HERRERA", "LAS MINAS", "EL TORO", "6-2-4"),
        Loc("HERRERA", "LAS MINAS", "LEONES", "6-2-5"),
        Loc("HERRERA", "LAS MINAS", "QUEBRADA DEL ROSARIO", "6-2-6"),
        Loc("HERRERA", "LAS MINAS", "QUEBRADA EL CIPRIAN", "6-2-7"),
        Loc("HERRERA", "LOS POZOS", "LOS POZOS (CABECERA)", "6-3-1"),
        Loc("HERRERA", "LOS POZOS", "CAPURI", "6-3-2"),
        Loc("HERRERA", "LOS POZOS", "EL CALABACITO", "6-3-3"),
        Loc("HERRERA", "LOS POZOS", "EL CEDRO", "6-3-4"),
        Loc("HERRERA", "LOS POZOS", "LA ARENA", "6-3-5"),
        Loc("HERRERA", "LOS POZOS", "LA PITALOSA", "6-3-6"),
        Loc("HERRERA", "LOS POZOS", "LOS CERRITOS", "6-3-7"),
        Loc("HERRERA", "LOS POZOS", "LOS CERROS DE PAJA", "6-3-8"),
        Loc("HERRERA", "LOS POZOS", "LAS LLANAS", "6-3-9"),
        Loc("HERRERA", "OCU", "OCU (CABECERA)", "6-4-1"),
        Loc("HERRERA", "OCU", "CERRO LARGO", "6-4-2"),
        Loc("HERRERA", "OCU", "LOS LLANOS", "6-4-3"),
        Loc("HERRERA", "OCU", "LLANO GRANDE", "6-4-4"),
        Loc("HERRERA", "OCU", "PEÑAS CHATAS", "6-4-5"),
        Loc("HERRERA", "OCU", "EL TIJERA", "6-4-6"),
        Loc("HERRERA", "OCU", "MENCHACA", "6-4-7"),
        Loc("HERRERA", "PARITA", "PARITA (CABECERA)", "6-5-1"),
        Loc("HERRERA", "PARITA", "CABUYA", "6-5-2"),
        Loc("HERRERA", "PARITA", "LOS CASTILLOS", "6-5-3"),
        Loc("HERRERA", "PARITA", "LLANO DE LA CRUZ", "6-5-4"),
        Loc("HERRERA", "PARITA", "PARIS", "6-5-5"),
        Loc("HERRERA", "PARITA", "PORTOBELILLO", "6-5-6"),
        Loc("HERRERA", "PARITA", "POTUGA", "6-5-7"),
        Loc("HERRERA", "PESE", "PESE (CABECERA)", "6-6-1"),
        Loc("HERRERA", "PESE", "LAS CABRAS", "6-6-2"),
        Loc("HERRERA", "PESE", "EL PAJARO", "6-6-3"),
        Loc("HERRERA", "PESE", "EL BARRERO", "6-6-4"),
        Loc("HERRERA", "PESE", "EL PEDREGOSO", "6-6-5"),
        Loc("HERRERA", "PESE", "EL CIRUELO", "6-6-6"),
        Loc("HERRERA", "PESE", "SABANAGRANDE", "6-6-7"),
        Loc("HERRERA", "PESE", "RINCON HONDO", "6-6-8"),
        Loc("HERRERA", "SANTA MARIA", "SANTA MARIA (CABECERA)", "6-7-1"),
        Loc("HERRERA", "SANTA MARIA", "CHUPAMPA", "6-7-2"),
        Loc("HERRERA", "SANTA MARIA", "EL RINCON", "6-7-3"),
        Loc("HERRERA", "SANTA MARIA", "EL LIMON", "6-7-4"),
        Loc("HERRERA", "SANTA MARIA", "LOS CANELOS", "6-7-5"),
        Loc("LOS SANTOS", "GUARARE", "GUARARE (CABECERA)", "7-1-1"),
        Loc("LOS SANTOS", "GUARARE", "EL ESPINAL", "7-1-2"),
        Loc("LOS SANTOS", "GUARARE", "EL MACANO", "7-1-3"),
        Loc("LOS SANTOS", "GUARARE", "GUARARE ARRIBA", "7-1-4"),
        Loc("LOS SANTOS", "GUARARE", "LA ENEA", "7-1-5"),
        Loc("LOS SANTOS", "GUARARE", "LA PASERA", "7-1-6"),
        Loc("LOS SANTOS", "GUARARE", "LAS TRANCAS", "7-1-7"),
        Loc("LOS SANTOS", "GUARARE", "LLANO ABAJO", "7-1-8"),
        Loc("LOS SANTOS", "GUARARE", "EL HATO", "7-1-9"),
        Loc("LOS SANTOS", "GUARARE", "PERALES", "7-1-10"),
        Loc("LOS SANTOS", "LAS TABLAS", "LAS TABLAS (CABECERA)", "7-2-1"),
        Loc("LOS SANTOS", "LAS TABLAS", "BAJO CORRAL", "7-2-2"),
        Loc("LOS SANTOS", "LAS TABLAS", "BAYANO", "7-2-3"),
        Loc("LOS SANTOS", "LAS TABLAS", "EL CARATE", "7-2-4"),
        Loc("LOS SANTOS", "LAS TABLAS", "EL COCAL", "7-2-5"),
        Loc("LOS SANTOS", "LAS TABLAS", "EL MANANTIAL", "7-2-6"),
        Loc("LOS SANTOS", "LAS TABLAS", "EL MUÑOZ", "7-2-7"),
        Loc("LOS SANTOS", "LAS TABLAS", "EL PEDREGOSO", "7-2-8"),
        Loc("LOS SANTOS", "LAS TABLAS", "LA LAJA", "7-2-9"),
        Loc("LOS SANTOS", "LAS TABLAS", "LA MIEL", "7-2-10"),
        Loc("LOS SANTOS", "LAS TABLAS", "LA PALMA", "7-2-11"),
        Loc("LOS SANTOS", "LAS TABLAS", "LA TIZA", "7-2-12"),
        Loc("LOS SANTOS", "LAS TABLAS", "LAS PALMITAS", "7-2-13"),
        Loc("LOS SANTOS", "LAS TABLAS", "LAS TABLAS ABAJO", "7-2-14"),
        Loc("LOS SANTOS", "LAS TABLAS", "NUARIO", "7-2-15"),
        Loc("LOS SANTOS", "LAS TABLAS", "PALMIRA", "7-2-16"),
        Loc("LOS SANTOS", "LAS TABLAS", "PEÑA BLANCA", "7-2-17"),
        Loc("LOS SANTOS", "LAS TABLAS", "RIO HONDO", "7-2-18"),
        Loc("LOS SANTOS", "LAS TABLAS", "SAN JOSE", "7-2-19"),
        Loc("LOS SANTOS", "LAS TABLAS", "SAN MIGUEL", "7-2-20"),
        Loc("LOS SANTOS", "LAS TABLAS", "SANTO DOMINGO", "7-2-21"),
        Loc("LOS SANTOS", "LAS TABLAS", "SESTEADERO", "7-2-22"),
        Loc("LOS SANTOS", "LAS TABLAS", "VALLE RICO", "7-2-23"),
        Loc("LOS SANTOS", "LAS TABLAS", "VALLERIQUITO", "7-2-24"),
        Loc("LOS SANTOS", "LOS SANTOS", "LA VILLA DE LOS SANTOS (CABECE", "7-3-1"),
        Loc("LOS SANTOS", "LOS SANTOS", "EL GUASIMO", "7-3-2"),
        Loc("LOS SANTOS", "LOS SANTOS", "LA COLORADA", "7-3-3"),
        Loc("LOS SANTOS", "LOS SANTOS", "LA ESPIGADILLA", "7-3-4"),
        Loc("LOS SANTOS", "LOS SANTOS", "LAS CRUCES", "7-3-5"),
        Loc("LOS SANTOS", "LOS SANTOS", "LAS GUABAS", "7-3-6"),
        Loc("LOS SANTOS", "LOS SANTOS", "LOS ANGELES", "7-3-7"),
        Loc("LOS SANTOS", "LOS SANTOS", "LOS OLIVOS", "7-3-8"),
        Loc("LOS SANTOS", "LOS SANTOS", "LLANO LARGO", "7-3-9"),
        Loc("LOS SANTOS", "LOS SANTOS", "SABANAGRANDE", "7-3-10"),
        Loc("LOS SANTOS", "LOS SANTOS", "SANTA ANA", "7-3-11"),
        Loc("LOS SANTOS", "LOS SANTOS", "TRES QUEBRADAS", "7-3-12"),
        Loc("LOS SANTOS", "LOS SANTOS", "AGUA BUENA", "7-3-13"),
        Loc("LOS SANTOS", "LOS SANTOS", "VILLA LOURDES", "7-3-14"),
        Loc("LOS SANTOS", "MACARACAS", "MACARACAS (CABECERA)", "7-4-1"),
        Loc("LOS SANTOS", "MACARACAS", "BAHIA HONDA", "7-4-2"),
        Loc("LOS SANTOS", "MACARACAS", "BAJOS DE GUERA", "7-4-3"),
        Loc("LOS SANTOS", "MACARACAS", "COROZAL", "7-4-4"),
        Loc("LOS SANTOS", "MACARACAS", "CHUPA", "7-4-5"),
        Loc("LOS SANTOS", "MACARACAS", "EL CEDRO", "7-4-6"),
        Loc("LOS SANTOS", "MACARACAS", "ESPINO AMARILLO", "7-4-7"),
        Loc("LOS SANTOS", "MACARACAS", "LA MESA", "7-4-8"),
        Loc("LOS SANTOS", "MACARACAS", "LAS PALMAS", "7-4-9"),
        Loc("LOS SANTOS", "MACARACAS", "LLANO DE PIEDRA", "7-4-10"),
        Loc("LOS SANTOS", "MACARACAS", "MOGOLLON", "7-4-11"),
        Loc("LOS SANTOS", "PEDASI", "PEDASI (CABECERA)", "7-5-1"),
        Loc("LOS SANTOS", "PEDASI", "LOS ASIENTOS", "7-5-2"),
        Loc("LOS SANTOS", "PEDASI", "MARIABE", "7-5-3"),
        Loc("LOS SANTOS", "PEDASI", "PURIO", "7-5-4"),
        Loc("LOS SANTOS", "PEDASI", "ORIA ARRIBA", "7-5-5"),
        Loc("LOS SANTOS", "POCRI", "POCRI", "7-6-1"),
        Loc("LOS SANTOS", "POCRI", "EL CAÑAFISTULO", "7-6-2"),
        Loc("LOS SANTOS", "POCRI", "LAJAMINA", "7-6-3"),
        Loc("LOS SANTOS", "POCRI", "PARAISO", "7-6-4"),
        Loc("LOS SANTOS", "POCRI", "PARITILLA", "7-6-5"),
        Loc("LOS SANTOS", "TONOSI", "TONOSI (CABECERA)", "7-7-1"),
        Loc("LOS SANTOS", "TONOSI", "ALTOS DE GUERA", "7-7-2"),
        Loc("LOS SANTOS", "TONOSI", "CAÑAS", "7-7-3"),
        Loc("LOS SANTOS", "TONOSI", "EL BEBEDERO", "7-7-4"),
        Loc("LOS SANTOS", "TONOSI", "EL CACAO", "7-7-5"),
        Loc("LOS SANTOS", "TONOSI", "EL CORTEZO", "7-7-6"),
        Loc("LOS SANTOS", "TONOSI", "FLORES", "7-7-7"),
        Loc("LOS SANTOS", "TONOSI", "GUANICO", "7-7-8"),
        Loc("LOS SANTOS", "TONOSI", "LA TRONOSA", "7-7-9"),
        Loc("LOS SANTOS", "TONOSI", "CAMBUTAL", "7-7-10"),
        Loc("LOS SANTOS", "TONOSI", "ISLA DE CAQAS", "7-7-11"),
        Loc("PANAMA", "BALBOA", "SAN MIGUEL (CABECERA)", "8-2-1"),
        Loc("PANAMA", "BALBOA", "LA ENSENADA", "8-2-2"),
        Loc("PANAMA", "BALBOA", "LA ESMERALDA", "8-2-3"),
        Loc("PANAMA", "BALBOA", "LA GUINEA", "8-2-4"),
        Loc("PANAMA", "BALBOA", "PEDRO GONZALEZ", "8-2-5"),
        Loc("PANAMA", "BALBOA", "SABOGA", "8-2-6"),
        Loc("PANAMA", "CHEPO", "CHEPO (CABECERA)", "8-5-1"),
        Loc("PANAMA", "CHEPO", "CAÑITA", "8-5-2"),
        Loc("PANAMA", "CHEPO", "CHEPILLO", "8-5-3"),
        Loc("PANAMA", "CHEPO", "EL LLANO", "8-5-4"),
        Loc("PANAMA", "CHEPO", "LAS MARGARITAS", "8-5-5"),
        Loc("PANAMA", "CHEPO", "SANTA CRUZ DE CHININA", "8-5-6"),
        Loc("PANAMA", "CHEPO", "COMARCA KUNA DE MADUNGANDI", "8-5-7"),
        Loc("PANAMA", "CHEPO", "TORTI", "8-5-8"),
        Loc("PANAMA", "CHIMAN", "CHIMAN (CABECERA)", "8-6-1"),
        Loc("PANAMA", "CHIMAN", "BRUJAS", "8-6-2"),
        Loc("PANAMA", "CHIMAN", "GONZALO VASQUEZ", "8-6-3"),
        Loc("PANAMA", "CHIMAN", "PASIGA", "8-6-4"),
        Loc("PANAMA", "CHIMAN", "UNION SANTEÑA", "8-6-5"),
        Loc("PANAMA", "PANAMA", "SAN FELIPE", "8-8-1"),
        Loc("PANAMA", "PANAMA", "EL CHORRILLO", "8-8-2"),
        Loc("PANAMA", "PANAMA", "SANTA ANA", "8-8-3"),
        Loc("PANAMA", "PANAMA", "LA EXPOSICION O CALIDONIA", "8-8-4"),
        Loc("PANAMA", "PANAMA", "CURUNDU", "8-8-5"),
        Loc("PANAMA", "PANAMA", "BETANIA", "8-8-6"),
        Loc("PANAMA", "PANAMA", "BELLA VISTA", "8-8-7"),
        Loc("PANAMA", "PANAMA", "PUEBLO NUEVO", "8-8-8"),
        Loc("PANAMA", "PANAMA", "SAN FRANCISCO", "8-8-9"),
        Loc("PANAMA", "PANAMA", "PARQUE LEFEVRE", "8-8-10"),
        Loc("PANAMA", "PANAMA", "RIO ABAJO", "8-8-11"),
        Loc("PANAMA", "PANAMA", "JUAN DIAZ", "8-8-12"),
        Loc("PANAMA", "PANAMA", "PEDREGAL", "8-8-13"),
        Loc("PANAMA", "PANAMA", "ANCON", "8-8-14"),
        Loc("PANAMA", "PANAMA", "CHILIBRE", "8-8-15"),
        Loc("PANAMA", "PANAMA", "LAS CUMBRES", "8-8-16"),
        Loc("PANAMA", "PANAMA", "PACORA", "8-8-17"),
        Loc("PANAMA", "PANAMA", "SAN MARTIN", "8-8-18"),
        Loc("PANAMA", "PANAMA", "TOCUMEN", "8-8-19"),
        Loc("PANAMA", "PANAMA", "LAS MAQANITAS", "8-8-20"),
        Loc("PANAMA", "PANAMA", "24 DE DICIEMBRE", "8-8-21"),
        Loc("PANAMA", "PANAMA", "ERNESTO CORDOBA CAMPOS", "8-8-22"),
        Loc("PANAMA", "PANAMA", "ALCALDE DIAZ", "8-8-23"),
        Loc("PANAMA", "PANAMA", "CAIMITILLO", "8-8-24"),
        Loc("PANAMA", "PANAMA", "DON BOSCO", "8-8-25"),
        Loc("PANAMA", "PANAMA", "LAS GARZAS", "8-8-26"),
        Loc("PANAMA", "SAN MIGUELITO", "AMELIA DENIS DE ICAZA", "8-10-1"),
        Loc("PANAMA", "SAN MIGUELITO", "BELISARIO PORRAS", "8-10-2"),
        Loc("PANAMA", "SAN MIGUELITO", "JOSE DOMINGO ESPINAR", "8-10-3"),
        Loc("PANAMA", "SAN MIGUELITO", "MATEO ITURRALDE", "8-10-4"),
        Loc("PANAMA", "SAN MIGUELITO", "VICTORIANO LORENZO", "8-10-5"),
        Loc("PANAMA", "SAN MIGUELITO", "ARNULFO ARIAS", "8-10-6"),
        Loc("PANAMA", "SAN MIGUELITO", "BELISARIO FRIAS", "8-10-7"),
        Loc("PANAMA", "SAN MIGUELITO", "OMAR TORRIJOS", "8-10-8"),
        Loc("PANAMA", "SAN MIGUELITO", "RUFINA ALFARO", "8-10-9"),
        Loc("PANAMA", "TABOGA", "TABOGA (CABECERA)", "8-11-1"),
        Loc("PANAMA", "TABOGA", "OTOQUE ORIENTE", "8-11-2"),
        Loc("PANAMA", "TABOGA", "OTOQUE OCCIDENTE", "8-11-3"),
        Loc("VERAGUAS", "ATALAYA", "ATALAYA (CABECERA)", "9-1-1"),
        Loc("VERAGUAS", "ATALAYA", "EL BARRITO", "9-1-2"),
        Loc("VERAGUAS", "ATALAYA", "LA MONTAÑUELA", "9-1-3"),
        Loc("VERAGUAS", "ATALAYA", "LA CARRILLO", "9-1-4"),
        Loc("VERAGUAS", "ATALAYA", "SAN ANTONIO", "9-1-5"),
        Loc("VERAGUAS", "CALOBRE", "CALOBRE (CABECERA)", "9-2-1"),
        Loc("VERAGUAS", "CALOBRE", "BARNIZAL", "9-2-2"),
        Loc("VERAGUAS", "CALOBRE", "CHITRA", "9-2-3"),
        Loc("VERAGUAS", "CALOBRE", "EL COCLA", "9-2-4"),
        Loc("VERAGUAS", "CALOBRE", "EL POTRERO", "9-2-5"),
        Loc("VERAGUAS", "CALOBRE", "LA LAGUNA", "9-2-6"),
        Loc("VERAGUAS", "CALOBRE", "LA RAYA DE CALOBRE", "9-2-7"),
        Loc("VERAGUAS", "CALOBRE", "LA TETILLA", "9-2-8"),
        Loc("VERAGUAS", "CALOBRE", "LA YEGUADA", "9-2-9"),
        Loc("VERAGUAS", "CALOBRE", "LAS GUIAS", "9-2-10"),
        Loc("VERAGUAS", "CALOBRE", "MONJARAS", "9-2-11"),
        Loc("VERAGUAS", "CALOBRE", "SAN JOSE", "9-2-12"),
        Loc("VERAGUAS", "CAÑAZAS", "CAÑAZAS (CABECERA)", "9-3-1"),
        Loc("VERAGUAS", "CAÑAZAS", "CERRO PLATA", "9-3-2"),
        Loc("VERAGUAS", "CAÑAZAS", "EL PICADOR", "9-3-3"),
        Loc("VERAGUAS", "CAÑAZAS", "LOS VALLES", "9-3-4"),
        Loc("VERAGUAS", "CAÑAZAS", "SAN JOSE", "9-3-5"),
        Loc("VERAGUAS", "CAÑAZAS", "SAN MARCELO", "9-3-6"),
        Loc("VERAGUAS", "CAÑAZAS", "EL AROMILLO", "9-3-7"),
        Loc("VERAGUAS", "LA MEZA", "LA MESA (CABECERA)", "9-4-1"),
        Loc("VERAGUAS", "LA MEZA", "BISVALLES", "9-4-2"),
        Loc("VERAGUAS", "LA MEZA", "BORO", "9-4-3"),
        Loc("VERAGUAS", "LA MEZA", "LLANO GRANDE", "9-4-4"),
        Loc("VERAGUAS", "LA MEZA", "SAN BARTOLO", "9-4-5"),
        Loc("VERAGUAS", "LA MEZA", "LOS MILAGROS", "9-4-6"),
        Loc("VERAGUAS", "LAS PALMAS", "LAS PALMAS (CABECERA)", "9-5-1"),
        Loc("VERAGUAS", "LAS PALMAS", "CERRO DE CASA", "9-5-2"),
        Loc("VERAGUAS", "LAS PALMAS", "COROZAL", "9-5-3"),
        Loc("VERAGUAS", "LAS PALMAS", "EL MARIA", "9-5-4"),
        Loc("VERAGUAS", "LAS PALMAS", "EL PRADO", "9-5-5"),
        Loc("VERAGUAS", "LAS PALMAS", "EL RINCON", "9-5-6"),
        Loc("VERAGUAS", "LAS PALMAS", "LOLA", "9-5-7"),
        Loc("VERAGUAS", "LAS PALMAS", "PIXVAE", "9-5-8"),
        Loc("VERAGUAS", "LAS PALMAS", "PUERTO VIDAL", "9-5-9"),
        Loc("VERAGUAS", "LAS PALMAS", "SAN MARTIN DE PORRES", "9-5-10"),
        Loc("VERAGUAS", "LAS PALMAS", "VIGUI", "9-5-11"),
        Loc("VERAGUAS", "LAS PALMAS", "ZAPOTILLO", "9-5-12"),
        Loc("VERAGUAS", "MONTIJO", "MONTIJO (CABECERA)", "9-6-1"),
        Loc("VERAGUAS", "MONTIJO", "ARENAS", "9-6-2"),
        Loc("VERAGUAS", "MONTIJO", "GOBERNADORA", "9-6-3"),
        Loc("VERAGUAS", "MONTIJO", "LA GARCEANA", "9-6-4"),
        Loc("VERAGUAS", "MONTIJO", "LEONES", "9-6-5"),
        Loc("VERAGUAS", "MONTIJO", "CEBACO", "9-6-6"),
        Loc("VERAGUAS", "MONTIJO", "COSTA HERMOSA", "9-6-7"),
        Loc("VERAGUAS", "MONTIJO", "UNION DEL NORTE", "9-6-8"),
        Loc("VERAGUAS", "MONTIJO", "TEBARIO", "9-6-9"),
        Loc("VERAGUAS", "MONTIJO", "EL PILON", "9-6-10"),
        Loc("VERAGUAS", "RIO DE JESUS", "RIO DE JESUS (CABECERA)", "9-7-1"),
        Loc("VERAGUAS", "RIO DE JESUS", "LAS HUACAS", "9-7-2"),
        Loc("VERAGUAS", "RIO DE JESUS", "LOS CASTILLOS", "9-7-3"),
        Loc("VERAGUAS", "RIO DE JESUS", "UTIRA", "9-7-4"),
        Loc("VERAGUAS", "RIO DE JESUS", "CATORCE DE NOVIEMBRE", "9-7-5"),
        Loc("VERAGUAS", "SAN FRANCISCO", "SAN FRANCISCO (CABECERA)", "9-8-1"),
        Loc("VERAGUAS", "SAN FRANCISCO", "CORRAL FALSO", "9-8-2"),
        Loc("VERAGUAS", "SAN FRANCISCO", "LOS HATILLOS", "9-8-3"),
        Loc("VERAGUAS", "SAN FRANCISCO", "REMANCE", "9-8-4"),
        Loc("VERAGUAS", "SAN FRANCISCO", "SAN JUAN", "9-8-5"),
        Loc("VERAGUAS", "SAN FRANCISCO", "SAN JOSE", "9-8-6"),
        Loc("VERAGUAS", "SANTA FE", "SANTA FE (CABECERA)", "9-9-1"),
        Loc("VERAGUAS", "SANTA FE", "CALOVEBORA", "9-9-2"),
        Loc("VERAGUAS", "SANTA FE", "EL ALTO", "9-9-3"),
        Loc("VERAGUAS", "SANTA FE", "EL CUAY", "9-9-4"),
        Loc("VERAGUAS", "SANTA FE", "EL PANTANO", "9-9-5"),
        Loc("VERAGUAS", "SANTA FE", "GATU O GATUCITO", "9-9-6"),
        Loc("VERAGUAS", "SANTA FE", "RIO LUIS", "9-9-7"),
        Loc("VERAGUAS", "SANTIAGO", "SANTIAGO (CABECERA)", "9-10-1"),
        Loc("VERAGUAS", "SANTIAGO", "LA COLORADA", "9-10-2"),
        Loc("VERAGUAS", "SANTIAGO", "LA PEÑA", "9-10-3"),
        Loc("VERAGUAS", "SANTIAGO", "LA RAYA DE SANTA MARIA", "9-10-4"),
        Loc("VERAGUAS", "SANTIAGO", "PONUGA", "9-10-5"),
        Loc("VERAGUAS", "SANTIAGO", "SAN PEDRO DEL ESPINO", "9-10-6"),
        Loc("VERAGUAS", "SANTIAGO", "CANTO DEL LLANO", "9-10-7"),
        Loc("VERAGUAS", "SANTIAGO", "LOS ALGARROBOS", "9-10-8"),
        Loc("VERAGUAS", "SANTIAGO", "CARLOS SANTANA AVILA", "9-10-9"),
        Loc("VERAGUAS", "SANTIAGO", "EDWIN FABREGA", "9-10-10"),
        Loc("VERAGUAS", "SANTIAGO", "SAN MARTIN DE PORRES", "9-10-11"),
        Loc("VERAGUAS", "SANTIAGO", "URRACA", "9-10-12"),
        Loc("VERAGUAS", "SONA", "SONA (CABECERA)", "9-11-1"),
        Loc("VERAGUAS", "SONA", "BAHIA HONDA", "9-11-2"),
        Loc("VERAGUAS", "SONA", "CALIDONIA", "9-11-3"),
        Loc("VERAGUAS", "SONA", "CATIVE", "9-11-4"),
        Loc("VERAGUAS", "SONA", "EL MARAÑON", "9-11-5"),
        Loc("VERAGUAS", "SONA", "GUARUMAL", "9-11-6"),
        Loc("VERAGUAS", "SONA", "LA SOLEDAD", "9-11-7"),
        Loc("VERAGUAS", "SONA", "QUEBRADA DE ORO", "9-11-8"),
        Loc("VERAGUAS", "SONA", "RIO GRANDE", "9-11-9"),
        Loc("VERAGUAS", "SONA", "RODEO VIEJO", "9-11-10"),
        Loc("VERAGUAS", "MARIATO", "LLANO DE CATIVAL O MARIATO (CABECERA)", "9-12-1"),
        Loc("VERAGUAS", "MARIATO", "ARENAS", "9-12-2"),
        Loc("VERAGUAS", "MARIATO", "EL CACAO", "9-12-3"),
        Loc("VERAGUAS", "MARIATO", "QUEBRO", "9-12-4"),
        Loc("VERAGUAS", "MARIATO", "TEBARIO", "9-12-5"),
        Loc("COMARCA KUNA YALA", "COMARCA KUNA YALA", "NARGANA (CABECERA)", "10-1-1"),
        Loc("COMARCA KUNA YALA", "COMARCA KUNA YALA", "AILIGANDI", "10-1-2"),
        Loc("COMARCA KUNA YALA", "COMARCA KUNA YALA", "PUERTO OBALDIA", "10-1-3"),
        Loc("COMARCA KUNA YALA", "COMARCA KUNA YALA", "TUBUALA", "10-1-4"),
        Loc("COMARCA EMBERA-WOUNAAN", "CEMACO", "CIRILO GUAINORA (CABECERA)", "11-1-1"),
        Loc("COMARCA EMBERA-WOUNAAN", "CEMACO", "LAJAS BLANCAS", "11-1-2"),
        Loc("COMARCA EMBERA-WOUNAAN", "CEMACO", "MANUEL ORTEGA", "11-1-3"),
        Loc("COMARCA EMBERA-WOUNAAN", "SAMBU", "RIO SABALO", "11-2-1"),
        Loc("COMARCA EMBERA-WOUNAAN", "SAMBU", "JINGURUDO", "11-2-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "SOLOY (CABECERA)", "12-1-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "BOCA DE BALSA", "12-1-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "CAMARON ARRIBA", "12-1-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "CERRO BANCO", "12-1-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "CERRO DE PATENA", "12-1-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "EMPLANADA DE CHORCHA", "12-1-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "NAMNONI", "12-1-7"),
        Loc("COMARCA NGÄBE-BUGLÉ", "BESIKO", "NIBA", "12-1-8"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "HATO PILON (CABECERA)", "12-2-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "CASCABEL", "12-2-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "HATO COROTU", "12-2-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "HATO CULANTRO", "12-2-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "HATO JOBO", "12-2-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "HATO JULI", "12-2-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "QUEBRADA DE LORO", "12-2-7"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MIRONO", "SALTO DUPI", "12-2-8"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "CHICHICA (CABECERA)", "12-3-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "ALTO CABALLERO", "12-3-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "BAKAMA", "12-3-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "CERRO CAÑA", "12-3-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "CERRO PUERCO", "12-3-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "KRUA", "12-3-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "MARACA", "12-3-7"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "NIBRA", "12-3-8"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "PEÑA BLANCA", "12-3-9"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "ROKA", "12-3-10"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "SITIO PRADO", "12-3-11"),
        Loc("COMARCA NGÄBE-BUGLÉ", "MUNA", "UMANI", "12-3-12"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NOLE DUIMA", "CERRO IGLESIAS (CABECERA)", "12-4-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NOLE DUIMA", "HATO CHAMI", "12-4-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NOLE DUIMA", "JADEBERI", "12-4-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NOLE DUIMA", "LAJERO", "12-4-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NOLE DUIMA", "SUSAMA", "12-4-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "BUENOS AIRES (CABECERA)", "12-5-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "AGUA DE SALUD", "12-5-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "ALTO DE JESUS", "12-5-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "CERRO PELADO", "12-5-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "EL BALE", "12-5-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "EL PAREDON", "12-5-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "EL PIRO", "12-5-7"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "GUAYABITO", "12-5-8"),
        Loc("COMARCA NGÄBE-BUGLÉ", "NURUM", "GUIBALE", "12-5-9"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "BISIRA (CABECERA)", "12-6-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "BURI", "12-6-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "GUARIVIARA", "12-6-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "GUORONI", "12-6-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "KANKINTU", "12-6-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "MUNUNI", "12-6-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "PIEDRA ROJA", "12-6-7"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "TUWAI", "12-6-8"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KANKINTU", "MAN CREEK", "12-6-9"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "KUSAPIN (CABECERA)", "12-7-1"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "BAHIA AZUL", "12-7-2"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "CALOVEBORA O SANTA CATALINA", "12-7-3"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "LOMA YUCA", "12-7-4"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "RIO CHIRIQUI", "12-7-5"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "TOBOBE", "12-7-6"),
        Loc("COMARCA NGÄBE-BUGLÉ", "KUSAPIN", "VALLE BONITO", "12-7-7"),
        Loc("PANAMA OESTE", "ARRAIJAN", "ARRAIJAN (CABECERA)", "13-1-1"),
        Loc("PANAMA OESTE", "ARRAIJAN", "BURUNGA", "13-1-2"),
        Loc("PANAMA OESTE", "ARRAIJAN", "CERRO SILVESTRE", "13-1-3"),
        Loc("PANAMA OESTE", "ARRAIJAN", "JUAN DEMOSTENES AROSEMENA", "13-1-4"),
        Loc("PANAMA OESTE", "ARRAIJAN", "NUEVO EMPERADOR", "13-1-5"),
        Loc("PANAMA OESTE", "ARRAIJAN", "SANTA CLARA", "13-1-6"),
        Loc("PANAMA OESTE", "ARRAIJAN", "VERACRUZ", "13-1-7"),
        Loc("PANAMA OESTE", "ARRAIJAN", "VISTA ALEGRE", "13-1-8"),
        Loc("PANAMA OESTE", "CAPIRA", "CAPIRA (CABECERA)", "13-2-1"),
        Loc("PANAMA OESTE", "CAPIRA", "CAIMITO", "13-2-2"),
        Loc("PANAMA OESTE", "CAPIRA", "CAMPANA", "13-2-3"),
        Loc("PANAMA OESTE", "CAPIRA", "CERMEÑO", "13-2-4"),
        Loc("PANAMA OESTE", "CAPIRA", "CIRI DE LOS SOTOS", "13-2-5"),
        Loc("PANAMA OESTE", "CAPIRA", "CIRI GRANDE", "13-2-6"),
        Loc("PANAMA OESTE", "CAPIRA", "EL CACAO", "13-2-7"),
        Loc("PANAMA OESTE", "CAPIRA", "LA TRINIDAD", "13-2-8"),
        Loc("PANAMA OESTE", "CAPIRA", "LAS OLLAS ARRIBA", "13-2-9"),
        Loc("PANAMA OESTE", "CAPIRA", "LIDICE", "13-2-10"),
        Loc("PANAMA OESTE", "CAPIRA", "VILLA CARMEN", "13-2-11"),
        Loc("PANAMA OESTE", "CAPIRA", "VILLA ROSARIO", "13-2-12"),
        Loc("PANAMA OESTE", "CAPIRA", "SANTA ROSA", "13-2-13"),
        Loc("PANAMA OESTE", "CHAME", "CHAME (CABECERA)", "13-3-1"),
        Loc("PANAMA OESTE", "CHAME", "BEJUCO", "13-3-2"),
        Loc("PANAMA OESTE", "CHAME", "BUENOS AIRES", "13-3-3"),
        Loc("PANAMA OESTE", "CHAME", "CABUYA", "13-3-4"),
        Loc("PANAMA OESTE", "CHAME", "CHICA", "13-3-5"),
        Loc("PANAMA OESTE", "CHAME", "EL LIBANO", "13-3-6"),
        Loc("PANAMA OESTE", "CHAME", "LAS LAJAS", "13-3-7"),
        Loc("PANAMA OESTE", "CHAME", "NUEVA GORGONA", "13-3-8"),
        Loc("PANAMA OESTE", "CHAME", "PUNTA CHAME", "13-3-9"),
        Loc("PANAMA OESTE", "CHAME", "SAJALICES", "13-3-10"),
        Loc("PANAMA OESTE", "CHAME", "SORA", "13-3-11"),
        Loc("PANAMA OESTE", "LA CHORRERA", "BARRIO BALBOA", "13-4-1"),
        Loc("PANAMA OESTE", "LA CHORRERA", "BARRIO COLON", "13-4-2"),
        Loc("PANAMA OESTE", "LA CHORRERA", "AMADOR", "13-4-3"),
        Loc("PANAMA OESTE", "LA CHORRERA", "AROSEMENA", "13-4-4"),
        Loc("PANAMA OESTE", "LA CHORRERA", "EL ARADO", "13-4-5"),
        Loc("PANAMA OESTE", "LA CHORRERA", "EL COCO", "13-4-6"),
        Loc("PANAMA OESTE", "LA CHORRERA", "FEUILLET", "13-4-7"),
        Loc("PANAMA OESTE", "LA CHORRERA", "GUADALUPE", "13-4-8"),
        Loc("PANAMA OESTE", "LA CHORRERA", "HERRERA", "13-4-9"),
        Loc("PANAMA OESTE", "LA CHORRERA", "HURTADO", "13-4-10"),
        Loc("PANAMA OESTE", "LA CHORRERA", "ITURRALDE", "13-4-11"),
        Loc("PANAMA OESTE", "LA CHORRERA", "LA REPRESA", "13-4-12"),
        Loc("PANAMA OESTE", "LA CHORRERA", "LOS DIAZ", "13-4-13"),
        Loc("PANAMA OESTE", "LA CHORRERA", "MENDOZA", "13-4-14"),
        Loc("PANAMA OESTE", "LA CHORRERA", "OBALDIA", "13-4-15"),
        Loc("PANAMA OESTE", "LA CHORRERA", "PLAYA LEONA", "13-4-16"),
        Loc("PANAMA OESTE", "LA CHORRERA", "PUERTO CAIMITO", "13-4-17"),
        Loc("PANAMA OESTE", "LA CHORRERA", "SANTA RITA", "13-4-18"),
        Loc("PANAMA OESTE", "SAN CARLOS", "SAN CARLOS (CABECERA)", "13-5-1"),
        Loc("PANAMA OESTE", "SAN CARLOS", "EL ESPINO", "13-5-2"),
        Loc("PANAMA OESTE", "SAN CARLOS", "EL HIGO", "13-5-3"),
        Loc("PANAMA OESTE", "SAN CARLOS", "GUAYABITO", "13-5-4"),
        Loc("PANAMA OESTE", "SAN CARLOS", "LA ERMITA", "13-5-5"),
        Loc("PANAMA OESTE", "SAN CARLOS", "LA LAGUNA", "13-5-6"),
        Loc("PANAMA OESTE", "SAN CARLOS", "LAS UVAS", "13-5-7"),
        Loc("PANAMA OESTE", "SAN CARLOS", "LOS LLANITOS", "13-5-8"),
        Loc("PANAMA OESTE", "SAN CARLOS", "SAN JOSE", "13-5-9"),
    )

    // Precomputed indexes for O(1) lookups
    val provinces: List<String> = LIST.map { it.province }.distinct().sorted()
    private val districtsByProvince: Map<String, List<String>> = LIST.groupBy { it.province }
        .mapValues { (_, rows) -> rows.map { it.district }.distinct().sorted() }
    private val corrsByProvDist: Map<Pair<String,String>, List<String>> = LIST.groupBy { it.province to it.district }
        .mapValues { (_, rows) -> rows.map { it.corregimiento }.distinct().sorted() }
    private val codeByTriple: Map<Triple<String,String,String>, String> =
        LIST.associate { Triple(it.province, it.district, it.corregimiento) to it.code }

    fun districts(province: String?): List<String> =
        if (province.isNullOrBlank()) emptyList() else districtsByProvince[province].orEmpty()

    fun corregimientos(province: String?, district: String?): List<String> =
        if (province.isNullOrBlank() || district.isNullOrBlank()) emptyList()
        else corrsByProvDist[province to district].orEmpty()

    fun codeFor(province: String?, district: String?, corregimiento: String?): String? =
        if (province.isNullOrBlank() || district.isNullOrBlank() || corregimiento.isNullOrBlank())
            null
        else codeByTriple[Triple(province, district, corregimiento)]
}