package com.teco.ventago.features.customers.ui.form.viewmodel

import com.teco.ventago.core.LoadableState
import com.teco.ventago.core.location.PanamaLocations
import com.teco.ventago.design_system.organism.LoadingBottomSheetState
import com.teco.ventago.features.invoicing.domain.TaxPayerType
import com.teco.ventago.features.invoicing.domain.models.FeCustomerType

enum class CustomerFormMode {
    CREATE,
    EDIT
}

internal const val DEFAULT_CUSTOMER_FORM_PROVINCE = "PANAMA"
internal const val DEFAULT_CUSTOMER_FORM_DISTRICT = "PANAMA"
internal const val DEFAULT_CUSTOMER_FORM_CORREGIMIENTO = "BELLA VISTA"
internal const val DEFAULT_CUSTOMER_FORM_ADDRESS_LINE = "Panama"
internal const val DEFAULT_FOREIGN_CUSTOMER_COUNTRY = "CO"

enum class CustomerFormStep {
    TYPE,
    MAIN_INFO,
    OPTIONAL_INFO
}

enum class CustomerForeignIdType(val code: String, val description: String) {
    PASSPORT("PASAPORTE", "Pasaporte"),
    OTHER("OTRO", "Otro")
}

data class CustomerCountryOption(
    val code: String,
    val name: String,
)

object CustomerCountries {
    val options: List<CustomerCountryOption> = listOf(
        CustomerCountryOption("AF", "Afganistán"),
        CustomerCountryOption("AL", "Albania"),
        CustomerCountryOption("DZ", "Argelia"),
        CustomerCountryOption("AS", "Samoa Americana"),
        CustomerCountryOption("AD", "Andorra"),
        CustomerCountryOption("AO", "Angola"),
        CustomerCountryOption("AI", "Anguilla"),
        CustomerCountryOption("AQ", "Antártida"),
        CustomerCountryOption("AR", "Argentina"),
        CustomerCountryOption("AM", "Armenia"),
        CustomerCountryOption("AW", "Aruba"),
        CustomerCountryOption("AU", "Australia"),
        CustomerCountryOption("AT", "Austria"),
        CustomerCountryOption("AZ", "Azerbaiyán"),
        CustomerCountryOption("BS", "Bahamas"),
        CustomerCountryOption("BH", "Baréin"),
        CustomerCountryOption("BD", "Bangladesh"),
        CustomerCountryOption("BB", "Barbados"),
        CustomerCountryOption("BY", "Bielorrusia"),
        CustomerCountryOption("BE", "Bélgica"),
        CustomerCountryOption("BZ", "Belize"),
        CustomerCountryOption("BJ", "Benín"),
        CustomerCountryOption("BM", "Bermuda"),
        CustomerCountryOption("BT", "Bután"),
        CustomerCountryOption("BO", "Bolivia"),
        CustomerCountryOption("BW", "Botswana"),
        CustomerCountryOption("BV", "Isla Bouvet"),
        CustomerCountryOption("BR", "Brasil"),
        CustomerCountryOption("BN", "Brunéi Darussalam"),
        CustomerCountryOption("BG", "Bulgaria"),
        CustomerCountryOption("BF", "Burkina Faso"),
        CustomerCountryOption("BI", "Burundi"),
        CustomerCountryOption("KH", "Camboya"),
        CustomerCountryOption("CM", "Camerún"),
        CustomerCountryOption("CA", "Canadá"),
        CustomerCountryOption("CV", "Cabo Verde"),
        CustomerCountryOption("KY", "Islas Caimán"),
        CustomerCountryOption("CF", "República Centroafricana"),
        CustomerCountryOption("TD", "Chad"),
        CustomerCountryOption("CL", "Chile"),
        CustomerCountryOption("CN", "China"),
        CustomerCountryOption("CX", "Isla de Navidad"),
        CustomerCountryOption("CC", "Islas Cocos (Keeling)"),
        CustomerCountryOption("CO", "Colombia"),
        CustomerCountryOption("KM", "Comoras"),
        CustomerCountryOption("CG", "Congo"),
        CustomerCountryOption("CK", "Islas Cook"),
        CustomerCountryOption("CR", "Costa Rica"),
        CustomerCountryOption("CI", "Costa de Marfil"),
        CustomerCountryOption("HR", "Croacia (Hrvatska)"),
        CustomerCountryOption("CU", "Cuba"),
        CustomerCountryOption("CY", "Chipre"),
        CustomerCountryOption("CZ", "República Checa"),
        CustomerCountryOption("DK", "Dinamarca"),
        CustomerCountryOption("DJ", "Yibuti"),
        CustomerCountryOption("DM", "Dominica"),
        CustomerCountryOption("DO", "República Dominicana"),
        CustomerCountryOption("EC", "Ecuador"),
        CustomerCountryOption("EG", "Egipto"),
        CustomerCountryOption("SV", "El Salvador"),
        CustomerCountryOption("GQ", "Guinea Ecuatorial"),
        CustomerCountryOption("ER", "Eritrea"),
        CustomerCountryOption("EE", "Estonia"),
        CustomerCountryOption("ET", "Etiopía"),
        CustomerCountryOption("FK", "Islas Malvinas"),
        CustomerCountryOption("FO", "Islas Feroe"),
        CustomerCountryOption("FJ", "Fiyi"),
        CustomerCountryOption("FI", "Finlandia"),
        CustomerCountryOption("FR", "Francia"),
        CustomerCountryOption("GF", "Guayana Francesa"),
        CustomerCountryOption("PF", "Polinesia Francesa"),
        CustomerCountryOption("GA", "Gabón"),
        CustomerCountryOption("GM", "Gambia"),
        CustomerCountryOption("GE", "Georgia"),
        CustomerCountryOption("DE", "Alemania"),
        CustomerCountryOption("GH", "Ghana"),
        CustomerCountryOption("GI", "Gibraltar"),
        CustomerCountryOption("GR", "Grecia"),
        CustomerCountryOption("GL", "Groenlandia"),
        CustomerCountryOption("GD", "Grenada"),
        CustomerCountryOption("GP", "Guadalupe"),
        CustomerCountryOption("GU", "Guam"),
        CustomerCountryOption("GT", "Guatemala"),
        CustomerCountryOption("GN", "Guinea"),
        CustomerCountryOption("GW", "Guinea-Bissau"),
        CustomerCountryOption("GY", "Guyana"),
        CustomerCountryOption("HT", "Haití"),
        CustomerCountryOption("HN", "Honduras"),
        CustomerCountryOption("HK", "Hong Kong"),
        CustomerCountryOption("HU", "Hungría"),
        CustomerCountryOption("IS", "Islandia"),
        CustomerCountryOption("IN", "India"),
        CustomerCountryOption("ID", "Indonesia"),
        CustomerCountryOption("IQ", "Irak"),
        CustomerCountryOption("IE", "Irlanda"),
        CustomerCountryOption("IL", "Israel"),
        CustomerCountryOption("IT", "Italia"),
        CustomerCountryOption("JM", "Jamaica"),
        CustomerCountryOption("JP", "Japón"),
        CustomerCountryOption("JO", "Jordania"),
        CustomerCountryOption("KZ", "Kazajistán"),
        CustomerCountryOption("KE", "Kenia"),
        CustomerCountryOption("KI", "Kiribati"),
        CustomerCountryOption("KR", "Corea, República de"),
        CustomerCountryOption("KW", "Kuwait"),
        CustomerCountryOption("KG", "Kirguistán"),
        CustomerCountryOption("LV", "Letonia"),
        CustomerCountryOption("LB", "Líbano"),
        CustomerCountryOption("LS", "Lesoto"),
        CustomerCountryOption("LR", "Liberia"),
        CustomerCountryOption("LY", "Jamahiriya Árabe Libia"),
        CustomerCountryOption("LI", "Liechtenstein"),
        CustomerCountryOption("LT", "Lituania"),
        CustomerCountryOption("LU", "Luxemburgo"),
        CustomerCountryOption("MO", "Macao"),
        CustomerCountryOption("MG", "Madagascar"),
        CustomerCountryOption("MW", "Malawi"),
        CustomerCountryOption("MY", "Malasia"),
        CustomerCountryOption("MV", "Maldivas"),
        CustomerCountryOption("ML", "Mali"),
        CustomerCountryOption("MT", "Malta"),
        CustomerCountryOption("MH", "Islas Marshall"),
        CustomerCountryOption("MQ", "Martinica"),
        CustomerCountryOption("MR", "Mauritania"),
        CustomerCountryOption("MU", "Mauricio"),
        CustomerCountryOption("YT", "Mayotte"),
        CustomerCountryOption("MX", "México"),
        CustomerCountryOption("MD", "Moldavia, República de"),
        CustomerCountryOption("MC", "Mónaco"),
        CustomerCountryOption("MN", "Mongolia"),
        CustomerCountryOption("MS", "Montserrat"),
        CustomerCountryOption("MA", "Marruecos"),
        CustomerCountryOption("MZ", "Mozambique"),
        CustomerCountryOption("MM", "Myanmar"),
        CustomerCountryOption("NA", "Namibia"),
        CustomerCountryOption("NR", "Nauru"),
        CustomerCountryOption("NP", "Nepal"),
        CustomerCountryOption("NL", "Países Bajos"),
        CustomerCountryOption("AN", "Antillas Neerlandesas"),
        CustomerCountryOption("NC", "Nueva Caledonia"),
        CustomerCountryOption("NZ", "Nueva Zelanda"),
        CustomerCountryOption("NI", "Nicaragua"),
        CustomerCountryOption("NE", "Níger"),
        CustomerCountryOption("NG", "Nigeria"),
        CustomerCountryOption("NU", "Niue"),
        CustomerCountryOption("NF", "Isla Norfolk"),
        CustomerCountryOption("MP", "Islas Marianas del Norte"),
        CustomerCountryOption("NO", "Noruega"),
        CustomerCountryOption("OM", "Omán"),
        CustomerCountryOption("PW", "Palau"),
        CustomerCountryOption("PA", "Panamá"),
        CustomerCountryOption("PG", "Papúa Nueva Guinea"),
        CustomerCountryOption("PY", "Paraguay"),
        CustomerCountryOption("PE", "Perú"),
        CustomerCountryOption("PH", "Filipinas"),
        CustomerCountryOption("PN", "Pitcairn"),
        CustomerCountryOption("PL", "Polonia"),
        CustomerCountryOption("PT", "Portugal"),
        CustomerCountryOption("PR", "Puerto Rico"),
        CustomerCountryOption("QA", "Qatar"),
        CustomerCountryOption("RE", "Reunión"),
        CustomerCountryOption("RO", "Rumanía"),
        CustomerCountryOption("RU", "Federación Rusa"),
        CustomerCountryOption("RW", "Ruanda"),
        CustomerCountryOption("KN", "San Cristóbal y Nieves"),
        CustomerCountryOption("LC", "Santa Lucía"),
        CustomerCountryOption("WS", "Samoa"),
        CustomerCountryOption("SM", "San Marino"),
        CustomerCountryOption("ST", "Santo Tomé y Príncipe"),
        CustomerCountryOption("SA", "Arabia Saudita"),
        CustomerCountryOption("SN", "Senegal"),
        CustomerCountryOption("SC", "Seychelles"),
        CustomerCountryOption("SL", "Sierra Leona"),
        CustomerCountryOption("SG", "Singapur"),
        CustomerCountryOption("SK", "Eslovaquia (República Eslovaca)"),
        CustomerCountryOption("SI", "Eslovenia"),
        CustomerCountryOption("SB", "Islas Salomón"),
        CustomerCountryOption("SO", "Somalia"),
        CustomerCountryOption("ZA", "Sudáfrica"),
        CustomerCountryOption("ES", "España"),
        CustomerCountryOption("LK", "Sri Lanka"),
        CustomerCountryOption("SH", "Santa Elena"),
        CustomerCountryOption("PM", "San Pedro y Miquelón"),
        CustomerCountryOption("SD", "Sudán"),
        CustomerCountryOption("SR", "Surinam"),
        CustomerCountryOption("SZ", "Suazilandia"),
        CustomerCountryOption("SE", "Suecia"),
        CustomerCountryOption("CH", "Suiza"),
        CustomerCountryOption("SY", "República Árabe Siria"),
        CustomerCountryOption("TW", "Taiwán, Provincia de China"),
        CustomerCountryOption("TJ", "Tayikistán"),
        CustomerCountryOption("TZ", "Tanzania, República Unida de"),
        CustomerCountryOption("TH", "Tailandia"),
        CustomerCountryOption("TG", "Togo"),
        CustomerCountryOption("TK", "Tokelau"),
        CustomerCountryOption("TO", "Tonga"),
        CustomerCountryOption("TT", "Trinidad y Tobago"),
        CustomerCountryOption("TN", "Túnez"),
        CustomerCountryOption("TR", "Turquía"),
        CustomerCountryOption("TM", "Turkmenistán"),
        CustomerCountryOption("TC", "Islas Turcas y Caicos"),
        CustomerCountryOption("TV", "Tuvalu"),
        CustomerCountryOption("UG", "Uganda"),
        CustomerCountryOption("UA", "Ucrania"),
        CustomerCountryOption("AE", "Emiratos Árabes Unidos"),
        CustomerCountryOption("GB", "Reino Unido"),
        CustomerCountryOption("US", "Estados Unidos"),
        CustomerCountryOption("UY", "Uruguay"),
        CustomerCountryOption("UZ", "Uzbekistán"),
        CustomerCountryOption("VU", "Vanuatu"),
        CustomerCountryOption("VE", "Venezuela"),
        CustomerCountryOption("VN", "Vietnam"),
        CustomerCountryOption("VG", "Islas Vírgenes Británicas"),
        CustomerCountryOption("VI", "Islas Vírgenes (EE. UU.)"),
        CustomerCountryOption("WF", "Islas Wallis y Futuna"),
        CustomerCountryOption("EH", "Sáhara Occidental"),
        CustomerCountryOption("YE", "Yemén"),
        CustomerCountryOption("ZM", "Zambia"),
        CustomerCountryOption("ZW", "Zimbabwe"),
    )
}

data class CustomerFormState(
    val mode: CustomerFormMode = CustomerFormMode.CREATE,
    val customerId: Long? = null,
    val currentStep: CustomerFormStep = CustomerFormStep.TYPE,
    val customerTypeSelected: Boolean = false,
    val addressExpanded: Boolean = false,

    val customerType: FeCustomerType = FeCustomerType.FINAL_CONSUMER,
    val customerTypeOptions: List<FeCustomerType> = listOf(
        FeCustomerType.FINAL_CONSUMER,
        FeCustomerType.CONTRIBUTING,
        FeCustomerType.GOVERNMENT,
        FeCustomerType.FOREIGNER,
    ),

    val taxPayerType: TaxPayerType = TaxPayerType.NATURAL,
    val name: String = "",
    val email: String = "",
    val phone: String = "",
    val ruc: String = "",
    val rucCheckDigit: String = "",
    val legalName: String = "",
    val rucError: String? = null,
    val cedulaCF: String = "",
    val cedulaError: String? = null,
    val foreignIdType: CustomerForeignIdType = CustomerForeignIdType.PASSPORT,
    val foreignIdNumber: String = "",
    val foreignIdNumberError: String? = null,
    val taxExempt: Boolean = false,
    val taxRetentionCode: String = "",
    val taxRetentionPercent: String = "",
    val taxRetentionPercentError: String? = null,

    val addressLine: String = "",
    val nameError: String? = null,
    val addressLineError: String? = null,
    val provinceError: String? = null,
    val districtError: String? = null,
    val corregimientoError: String? = null,
    val selectedProvince: String? = null,
    val selectedDistrict: String? = null,
    val selectedCorregimiento: String? = null,
    val selectedCountryCode: String = DEFAULT_FOREIGN_CUSTOMER_COUNTRY,

    val provinceOptions: List<String> = PanamaLocations.provinces,
    val districtOptions: List<String> = emptyList(),
    val corregimientoOptions: List<String> = emptyList(),
    val countryOptions: List<CustomerCountryOption> = CustomerCountries.options.filterNot { it.code == "PA" },

    val invoicingEnabled: Boolean = false,
    val isFetching: Boolean = false,
    val validationMessage: String? = null,
    val errorMessage: String? = null,

    override val loadingBottomSheet: LoadingBottomSheetState = LoadingBottomSheetState(),
) : LoadableState<CustomerFormState> {
    val isEditMode: Boolean get() = mode == CustomerFormMode.EDIT

    override fun withLoading(state: LoadingBottomSheetState): CustomerFormState =
        copy(loadingBottomSheet = state)
}

sealed class CustomerFormUiEvent {
    data object Saved : CustomerFormUiEvent()
    data class ValidationError(val message: String) : CustomerFormUiEvent()
}
