package com.teco.ventago.features.customers.ui.form.viewmodel

import com.teco.ventago.core.LoadableState
import com.teco.ventago.core.location.PanamaLocations
import com.teco.ventago.design_system.organism.LoadingBottomSheetState
import com.teco.ventago.features.invoicing.domain.TaxPayerType
import com.teco.ventago.features.invoicing.domain.models.FeCustomerType

enum class CustomerFormMode {
    CREATE,
    EDIT
}

enum class CustomerForeignIdType(val code: String, val description: String) {
    PASSPORT("PASAPORTE", "Pasaporte"),
    OTHER("OTRO", "Otro")
}

data class CustomerCountryOption(
    val code: String,
    val name: String,
)

object CustomerCountries {
    val options: List<CustomerCountryOption> = listOf(
        CustomerCountryOption("AF", "Afghanistan"),
        CustomerCountryOption("AL", "Albania"),
        CustomerCountryOption("DZ", "Algeria"),
        CustomerCountryOption("AS", "American Samoa"),
        CustomerCountryOption("AD", "Andorra"),
        CustomerCountryOption("AO", "Angola"),
        CustomerCountryOption("AI", "Anguilla"),
        CustomerCountryOption("AQ", "Antarctica"),
        CustomerCountryOption("AR", "Argentina"),
        CustomerCountryOption("AM", "Armenia"),
        CustomerCountryOption("AW", "Aruba"),
        CustomerCountryOption("AU", "Australia"),
        CustomerCountryOption("AT", "Austria"),
        CustomerCountryOption("AZ", "Azerbaijan"),
        CustomerCountryOption("BS", "Bahamas"),
        CustomerCountryOption("BH", "Bahrain"),
        CustomerCountryOption("BD", "Bangladesh"),
        CustomerCountryOption("BB", "Barbados"),
        CustomerCountryOption("BY", "Belarus"),
        CustomerCountryOption("BE", "Belgium"),
        CustomerCountryOption("BZ", "Belize"),
        CustomerCountryOption("BJ", "Benin"),
        CustomerCountryOption("BM", "Bermuda"),
        CustomerCountryOption("BT", "Bhutan"),
        CustomerCountryOption("BO", "Bolivia"),
        CustomerCountryOption("BW", "Botswana"),
        CustomerCountryOption("BV", "Bouvet Island"),
        CustomerCountryOption("BR", "Brazil"),
        CustomerCountryOption("BN", "Brunei Darussalam"),
        CustomerCountryOption("BG", "Bulgaria"),
        CustomerCountryOption("BF", "Burkina Faso"),
        CustomerCountryOption("BI", "Burundi"),
        CustomerCountryOption("KH", "Cambodia"),
        CustomerCountryOption("CM", "Cameroon"),
        CustomerCountryOption("CA", "Canada"),
        CustomerCountryOption("CV", "Cape Verde"),
        CustomerCountryOption("KY", "Cayman Islands"),
        CustomerCountryOption("CF", "Central African Republic"),
        CustomerCountryOption("TD", "Chad"),
        CustomerCountryOption("CL", "Chile"),
        CustomerCountryOption("CN", "China"),
        CustomerCountryOption("CX", "Christmas Island"),
        CustomerCountryOption("CC", "Cocos (Keeling) Islands"),
        CustomerCountryOption("CO", "Colombia"),
        CustomerCountryOption("KM", "Comoros"),
        CustomerCountryOption("CG", "Congo"),
        CustomerCountryOption("CK", "Cook Islands"),
        CustomerCountryOption("CR", "Costa Rica"),
        CustomerCountryOption("CI", "Cote d'Ivoire"),
        CustomerCountryOption("HR", "Croatia (Hrvatska)"),
        CustomerCountryOption("CU", "Cuba"),
        CustomerCountryOption("CY", "Cyprus"),
        CustomerCountryOption("CZ", "Czech Republic"),
        CustomerCountryOption("DK", "Denmark"),
        CustomerCountryOption("DJ", "Djibouti"),
        CustomerCountryOption("DM", "Dominica"),
        CustomerCountryOption("DO", "Dominican Republic"),
        CustomerCountryOption("EC", "Ecuador"),
        CustomerCountryOption("EG", "Egypt"),
        CustomerCountryOption("SV", "El Salvador"),
        CustomerCountryOption("GQ", "Equatorial Guinea"),
        CustomerCountryOption("ER", "Eritrea"),
        CustomerCountryOption("EE", "Estonia"),
        CustomerCountryOption("ET", "Ethiopia"),
        CustomerCountryOption("FK", "Falkland Islands (Malvinas)"),
        CustomerCountryOption("FO", "Faroe Islands"),
        CustomerCountryOption("FJ", "Fiji"),
        CustomerCountryOption("FI", "Finland"),
        CustomerCountryOption("FR", "France"),
        CustomerCountryOption("GF", "French Guiana"),
        CustomerCountryOption("PF", "French Polynesia"),
        CustomerCountryOption("GA", "Gabon"),
        CustomerCountryOption("GM", "Gambia"),
        CustomerCountryOption("GE", "Georgia"),
        CustomerCountryOption("DE", "Germany"),
        CustomerCountryOption("GH", "Ghana"),
        CustomerCountryOption("GI", "Gibraltar"),
        CustomerCountryOption("GR", "Greece"),
        CustomerCountryOption("GL", "Greenland"),
        CustomerCountryOption("GD", "Grenada"),
        CustomerCountryOption("GP", "Guadeloupe"),
        CustomerCountryOption("GU", "Guam"),
        CustomerCountryOption("GT", "Guatemala"),
        CustomerCountryOption("GN", "Guinea"),
        CustomerCountryOption("GW", "Guinea-Bissau"),
        CustomerCountryOption("GY", "Guyana"),
        CustomerCountryOption("HT", "Haiti"),
        CustomerCountryOption("HN", "Honduras"),
        CustomerCountryOption("HK", "Hong Kong"),
        CustomerCountryOption("HU", "Hungary"),
        CustomerCountryOption("IS", "Iceland"),
        CustomerCountryOption("IN", "India"),
        CustomerCountryOption("ID", "Indonesia"),
        CustomerCountryOption("IQ", "Iraq"),
        CustomerCountryOption("IE", "Ireland"),
        CustomerCountryOption("IL", "Israel"),
        CustomerCountryOption("IT", "Italy"),
        CustomerCountryOption("JM", "Jamaica"),
        CustomerCountryOption("JP", "Japan"),
        CustomerCountryOption("JO", "Jordan"),
        CustomerCountryOption("KZ", "Kazakhstan"),
        CustomerCountryOption("KE", "Kenya"),
        CustomerCountryOption("KI", "Kiribati"),
        CustomerCountryOption("KR", "Korea, Republic of"),
        CustomerCountryOption("KW", "Kuwait"),
        CustomerCountryOption("KG", "Kyrgyzstan"),
        CustomerCountryOption("LV", "Latvia"),
        CustomerCountryOption("LB", "Lebanon"),
        CustomerCountryOption("LS", "Lesotho"),
        CustomerCountryOption("LR", "Liberia"),
        CustomerCountryOption("LY", "Libyan Arab Jamahiriya"),
        CustomerCountryOption("LI", "Liechtenstein"),
        CustomerCountryOption("LT", "Lithuania"),
        CustomerCountryOption("LU", "Luxembourg"),
        CustomerCountryOption("MO", "Macau"),
        CustomerCountryOption("MG", "Madagascar"),
        CustomerCountryOption("MW", "Malawi"),
        CustomerCountryOption("MY", "Malaysia"),
        CustomerCountryOption("MV", "Maldives"),
        CustomerCountryOption("ML", "Mali"),
        CustomerCountryOption("MT", "Malta"),
        CustomerCountryOption("MH", "Marshall Islands"),
        CustomerCountryOption("MQ", "Martinique"),
        CustomerCountryOption("MR", "Mauritania"),
        CustomerCountryOption("MU", "Mauritius"),
        CustomerCountryOption("YT", "Mayotte"),
        CustomerCountryOption("MX", "Mexico"),
        CustomerCountryOption("MD", "Moldova, Republic of"),
        CustomerCountryOption("MC", "Monaco"),
        CustomerCountryOption("MN", "Mongolia"),
        CustomerCountryOption("MS", "Montserrat"),
        CustomerCountryOption("MA", "Morocco"),
        CustomerCountryOption("MZ", "Mozambique"),
        CustomerCountryOption("MM", "Myanmar"),
        CustomerCountryOption("NA", "Namibia"),
        CustomerCountryOption("NR", "Nauru"),
        CustomerCountryOption("NP", "Nepal"),
        CustomerCountryOption("NL", "Netherlands"),
        CustomerCountryOption("AN", "Netherlands Antilles"),
        CustomerCountryOption("NC", "New Caledonia"),
        CustomerCountryOption("NZ", "New Zealand"),
        CustomerCountryOption("NI", "Nicaragua"),
        CustomerCountryOption("NE", "Niger"),
        CustomerCountryOption("NG", "Nigeria"),
        CustomerCountryOption("NU", "Niue"),
        CustomerCountryOption("NF", "Norfolk Island"),
        CustomerCountryOption("MP", "Northern Mariana Islands"),
        CustomerCountryOption("NO", "Norway"),
        CustomerCountryOption("OM", "Oman"),
        CustomerCountryOption("PW", "Palau"),
        CustomerCountryOption("PA", "Panama"),
        CustomerCountryOption("PG", "Papua New Guinea"),
        CustomerCountryOption("PY", "Paraguay"),
        CustomerCountryOption("PE", "Peru"),
        CustomerCountryOption("PH", "Philippines"),
        CustomerCountryOption("PN", "Pitcairn"),
        CustomerCountryOption("PL", "Poland"),
        CustomerCountryOption("PT", "Portugal"),
        CustomerCountryOption("PR", "Puerto Rico"),
        CustomerCountryOption("QA", "Qatar"),
        CustomerCountryOption("RE", "Reunion"),
        CustomerCountryOption("RO", "Romania"),
        CustomerCountryOption("RU", "Russian Federation"),
        CustomerCountryOption("RW", "Rwanda"),
        CustomerCountryOption("KN", "Saint Kitts and Nevis"),
        CustomerCountryOption("LC", "Saint LUCIA"),
        CustomerCountryOption("WS", "Samoa"),
        CustomerCountryOption("SM", "San Marino"),
        CustomerCountryOption("ST", "Sao Tome and Principe"),
        CustomerCountryOption("SA", "Saudi Arabia"),
        CustomerCountryOption("SN", "Senegal"),
        CustomerCountryOption("SC", "Seychelles"),
        CustomerCountryOption("SL", "Sierra Leone"),
        CustomerCountryOption("SG", "Singapore"),
        CustomerCountryOption("SK", "Slovakia (Slovak Republic)"),
        CustomerCountryOption("SI", "Slovenia"),
        CustomerCountryOption("SB", "Solomon Islands"),
        CustomerCountryOption("SO", "Somalia"),
        CustomerCountryOption("ZA", "South Africa"),
        CustomerCountryOption("ES", "Spain"),
        CustomerCountryOption("LK", "Sri Lanka"),
        CustomerCountryOption("SH", "St. Helena"),
        CustomerCountryOption("PM", "St. Pierre and Miquelon"),
        CustomerCountryOption("SD", "Sudan"),
        CustomerCountryOption("SR", "Suriname"),
        CustomerCountryOption("SZ", "Swaziland"),
        CustomerCountryOption("SE", "Sweden"),
        CustomerCountryOption("CH", "Switzerland"),
        CustomerCountryOption("SY", "Syrian Arab Republic"),
        CustomerCountryOption("TW", "Taiwan, Province of China"),
        CustomerCountryOption("TJ", "Tajikistan"),
        CustomerCountryOption("TZ", "Tanzania, United Republic of"),
        CustomerCountryOption("TH", "Thailand"),
        CustomerCountryOption("TG", "Togo"),
        CustomerCountryOption("TK", "Tokelau"),
        CustomerCountryOption("TO", "Tonga"),
        CustomerCountryOption("TT", "Trinidad and Tobago"),
        CustomerCountryOption("TN", "Tunisia"),
        CustomerCountryOption("TR", "Turkey"),
        CustomerCountryOption("TM", "Turkmenistan"),
        CustomerCountryOption("TC", "Turks and Caicos Islands"),
        CustomerCountryOption("TV", "Tuvalu"),
        CustomerCountryOption("UG", "Uganda"),
        CustomerCountryOption("UA", "Ukraine"),
        CustomerCountryOption("AE", "United Arab Emirates"),
        CustomerCountryOption("GB", "United Kingdom"),
        CustomerCountryOption("US", "United States"),
        CustomerCountryOption("UY", "Uruguay"),
        CustomerCountryOption("UZ", "Uzbekistan"),
        CustomerCountryOption("VU", "Vanuatu"),
        CustomerCountryOption("VE", "Venezuela"),
        CustomerCountryOption("VN", "Viet Nam"),
        CustomerCountryOption("VG", "Virgin Islands (British)"),
        CustomerCountryOption("VI", "Virgin Islands (U.S.)"),
        CustomerCountryOption("WF", "Wallis and Futuna Islands"),
        CustomerCountryOption("EH", "Western Sahara"),
        CustomerCountryOption("YE", "Yemen"),
        CustomerCountryOption("ZM", "Zambia"),
        CustomerCountryOption("ZW", "Zimbabwe"),
    )
}

data class CustomerFormState(
    val mode: CustomerFormMode = CustomerFormMode.CREATE,
    val customerId: Long? = null,

    val customerType: FeCustomerType = FeCustomerType.FINAL_CONSUMER,
    val customerTypeOptions: List<FeCustomerType> = listOf(
        FeCustomerType.FINAL_CONSUMER,
        FeCustomerType.CONTRIBUTING,
        FeCustomerType.GOVERNMENT,
        FeCustomerType.FOREIGNER,
    ),

    val taxPayerType: TaxPayerType = TaxPayerType.NATURAL,
    val name: String = "",
    val email: String = "",
    val phone: String = "",
    val ruc: String = "",
    val rucCheckDigit: String = "",
    val legalName: String = "",
    val cedulaCF: String = "",
    val cedulaError: String? = null,
    val foreignIdType: CustomerForeignIdType = CustomerForeignIdType.PASSPORT,
    val foreignIdNumber: String = "",
    val taxExempt: Boolean = false,
    val taxRetentionCode: String = "",
    val taxRetentionPercent: String = "",

    val addressLine: String = "",
    val nameError: String? = null,
    val addressLineError: String? = null,
    val provinceError: String? = null,
    val districtError: String? = null,
    val corregimientoError: String? = null,
    val selectedProvince: String? = null,
    val selectedDistrict: String? = null,
    val selectedCorregimiento: String? = null,
    val selectedCountryCode: String = "PA",

    val provinceOptions: List<String> = PanamaLocations.provinces,
    val districtOptions: List<String> = emptyList(),
    val corregimientoOptions: List<String> = emptyList(),
    val countryOptions: List<CustomerCountryOption> = CustomerCountries.options,

    val invoicingEnabled: Boolean = false,
    val isFetching: Boolean = false,
    val errorMessage: String? = null,

    override val loadingBottomSheet: LoadingBottomSheetState = LoadingBottomSheetState(),
) : LoadableState<CustomerFormState> {
    val isEditMode: Boolean get() = mode == CustomerFormMode.EDIT

    override fun withLoading(state: LoadingBottomSheetState): CustomerFormState =
        copy(loadingBottomSheet = state)
}

sealed class CustomerFormUiEvent {
    data object Saved : CustomerFormUiEvent()
    data class ValidationError(val message: String) : CustomerFormUiEvent()
}
